import os
from docx import Document

# Document 1: company_profile.docx
doc1 = Document()
doc1.add_heading('Company Profile', 0)
doc1.add_heading('Company Overview', level=1)
doc1.add_paragraph('BidFactory Solutions is a leading provider of innovative software and technology services. We specialize in transforming enterprise workflows through intelligent automation and secure data management.')
doc1.add_heading('Years of Experience', level=1)
doc1.add_paragraph('Founded in 2012, BidFactory Solutions has over 14 years of experience delivering robust business-to-business software solutions.')
doc1.add_heading('Team Capabilities', level=1)
doc1.add_paragraph('Our global team consists of over 500 seasoned software engineers, data scientists, and cloud architects dedicated to delivering excellence.')
doc1.add_heading('Locations', level=1)
doc1.add_paragraph('We are headquartered in San Francisco, CA, with primary regional offices in New York, London, and Singapore.')
doc1.add_heading('Service Areas', level=1)
doc1.add_paragraph('We provide end-to-end services in cloud architecture, AI and Machine Learning, software development, and enterprise managed services.')
doc1.save('data/knowledge_base/company_profile.docx')

# Document 2: technical_capabilities.docx
doc2 = Document()
doc2.add_heading('Technical Capabilities', 0)
doc2.add_heading('Cloud Platforms', level=1)
doc2.add_paragraph('We securely design and host solutions across all major cloud platforms, including Amazon Web Services (AWS), Microsoft Azure, and Google Cloud Platform (GCP).')
doc2.add_heading('Software Development', level=1)
doc2.add_paragraph('Our software development lifecycle leverages Agile methodologies, utilizing Python, TypeScript, and Go for highly scalable backends and resilient frontends.')
doc2.add_heading('AI and ML', level=1)
doc2.add_paragraph('We employ cutting-edge AI and Machine Learning technologies to power our intelligent systems, utilizing frameworks like PyTorch and TensorFlow.')
doc2.add_heading('APIs', level=1)
doc2.add_paragraph('Our solutions rely on robust RESTful APIs and GraphQL to ensure seamless integration and data exchange across enterprise systems.')
doc2.add_heading('Deployment and Scalability', level=1)
doc2.add_paragraph('Using Kubernetes and Docker, we provide containerized deployments that auto-scale to meet varying traffic demands seamlessly.')
doc2.save('data/knowledge_base/technical_capabilities.docx')

# Document 3: security_and_compliance.docx
doc3 = Document()
doc3.add_heading('Security and Compliance', 0)
doc3.add_heading('Security Controls', level=1)
doc3.add_paragraph('We implement stringent security controls including continuous vulnerability scanning, intrusion detection systems (IDS), and web application firewalls.')
doc3.add_heading('Data Protection', level=1)
doc3.add_paragraph('All customer data is AES-256 encrypted at rest and TLS 1.3 encrypted in transit. We guarantee no unauthorized data exfiltration.')
doc3.add_heading('Access Control', level=1)
doc3.add_paragraph('Access control is governed by strict Role-Based Access Control (RBAC) and mandatory multi-factor authentication (MFA).')
doc3.add_heading('Certifications', level=1)
doc3.add_paragraph('We hold official ISO 27001 certification for Information Security Management and SOC 2 Type II attestation.')
doc3.add_heading('Compliance Capabilities', level=1)
doc3.add_paragraph('Our software supports enterprise compliance requirements for GDPR and HIPAA by offering selective geographical data residency and full audit trails.')
doc3.save('data/knowledge_base/security_and_compliance.docx')

# Document 4: sla_and_support.docx
doc4 = Document()
doc4.add_heading('SLA and Support', 0)
doc4.add_heading('Availability SLA', level=1)
doc4.add_paragraph('BidFactory Solutions provides an industry-leading Service Level Agreement (SLA) guaranteeing 99.9% uptime and availability for all enterprise clients.')
doc4.add_heading('Support Hours', level=1)
doc4.add_paragraph('We provide 24/7/365 global support. Our support team is online and available around the clock.')
doc4.add_heading('Response Times', level=1)
doc4.add_paragraph('We guarantee a response time of under 1 hour for all Severity 1 (critical) production incidents.')
doc4.add_heading('Incident Handling', level=1)
doc4.add_paragraph('Our incident handling protocol involves immediate triage by Level 2 engineers and continuous updates every 30 minutes until resolution.')
doc4.add_heading('Escalation', level=1)
doc4.add_paragraph('Issues that remain unresolved for two hours are automatically escalated to the executive engineering team for expedited remediation.')
doc4.save('data/knowledge_base/sla_and_support.docx')

# Document 5: ai_ml_capabilities.docx
doc5 = Document()
doc5.add_heading('AI and ML Capabilities', 0)
doc5.add_heading('Machine Learning', level=1)
doc5.add_paragraph('Our machine learning practice trains and fine-tunes custom predictive engines to support intelligent enterprise decision-making.')
doc5.add_heading('Natural Language Processing (NLP)', level=1)
doc5.add_paragraph('We leverage advanced NLP models natively integrated into our RAG systems to parse complex documents and extract meaningful insights.')
doc5.add_heading('Computer Vision', level=1)
doc5.add_paragraph('Our computer vision models specialize in automated document OCR and layout detection for rapid PDF processing.')
doc5.add_heading('Model Deployment', level=1)
doc5.add_paragraph('We deploy AI models seamlessly utilizing scalable Triton Inference Server clusters equipped with GPU acceleration.')
doc5.add_heading('MLOps', level=1)
doc5.add_paragraph('Our comprehensive MLOps pipeline guarantees robust model tracking, automated drift detection, and continuous retraining capabilities.')
doc5.save('data/knowledge_base/ai_ml_capabilities.docx')

# Document 6: previous_projects.docx
doc6 = Document()
doc6.add_heading('Previous Projects', 0)
doc6.add_heading('Project Alpha - Financial Automation', level=1)
doc6.add_paragraph('Description: We partnered with Global Bank Corp to automate their loan origination system leveraging intelligent document extraction.')
doc6.add_paragraph('Technologies: Python, Kubernetes, AWS, PyTorch.')
doc6.add_paragraph('Outcomes: Reduced manual processing time by 40% and improved accuracy to 99%.')
doc6.add_paragraph('Industry: Finance and Banking.')
doc6.add_heading('Project Beta - Healthcare Data Lake', level=1)
doc6.add_paragraph('Description: Built a HIPAA-compliant healthcare data lake for National Health Partners to aggregate millions of patient records safely.')
doc6.add_paragraph('Technologies: Azure, Databricks, PostgreSQL.')
doc6.add_paragraph('Outcomes: Unified multi-hospital data silos and enabled rapid analytics query resolution.')
doc6.add_paragraph('Industry: Healthcare.')
doc6.save('data/knowledge_base/previous_projects.docx')

# Document 7: service_catalog.docx
doc7 = Document()
doc7.add_heading('Service Catalog', 0)
doc7.add_heading('Services Offered', level=1)
doc7.add_paragraph('BidFactory Solutions provides a varied suite of consulting, implementation, and managed automation services to accelerate digital transformation.')
doc7.add_heading('Implementation', level=1)
doc7.add_paragraph('Our implementation service handles the end-to-end integration of our SaaS tools into your unique on-premise or cloud environments.')
doc7.add_heading('Consulting', level=1)
doc7.add_paragraph('We offer strategic consulting to assist enterprises in redesigning outdated manual workflows utilizing modern AI technologies.')
doc7.add_heading('Managed Services', level=1)
doc7.add_paragraph('We provide remote administration and proactive monitoring of your infrastructure guaranteeing optimal health and stability.')
doc7.add_heading('Continuous Support', level=1)
doc7.add_paragraph('Dedicated technical account managers provide ongoing continuous support aligning your operations with our technology updates.')
doc7.save('data/knowledge_base/service_catalog.docx')

# Document 8: certifications_and_policies.docx
doc8 = Document()
doc8.add_heading('Certifications and Policies', 0)
doc8.add_heading('Security Policies', level=1)
doc8.add_paragraph('We enforce a zero-trust network architecture policy, where every device, user, and network flow is verified strictly without implicit trust.')
doc8.add_heading('Data Retention', level=1)
doc8.add_paragraph('Our data retention policy defaults to keeping logs for a minimum of 1 year, and client information is permanently destroyed 30 days after contract termination.')
doc8.add_heading('Backup and Recovery', level=1)
doc8.add_paragraph('We execute automated daily backups with a Recovery Point Objective (RPO) of 24 hours and a Recovery Time Objective (RTO) of 1 hour.')
doc8.save('data/knowledge_base/certifications_and_policies.docx')

print('Successfully generated 8 realistic demo knowledge base documents.')
